apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: muescheli
  labels:
    app: muescheli
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: muescheli
        release: muescheli
    spec:
      imagePullSecrets:
        - name: monoregistry
      containers:
        - name: muescheli
          image: "monostream/muescheli:latest"
          imagePullPolicy: Always
          env:
          - name: CLAMD_HOST
            value: localhost
          - name: CLAMD_PORT
            value: '3310'
          ports:
            - containerPort: 8091
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8091
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8091
        - name: clamd
          image: "monostream/clamav:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 3310
            name: api
            protocol: TCP
          livenessProbe:
            exec:
              command:
              - /readiness.sh
            initialDelaySeconds: 90
            timeoutSeconds: 10
            periodSeconds: 300
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: muescheli
  labels:
    app: muescheli
spec:
  type: NodePort
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
      name: muescheli
  selector:
    app: muescheli
    release: muescheli