apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: muescheli
  labels:
    app: muescheli
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      # set to 0 to make sure that there is no downtime on a deployment update
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: muescheli
        release: muescheli
    spec:
      imagePullSecrets:
        - name: monoregistry
      containers:
        - name: muescheli
          image: "monostream/muescheli:latest"
          imagePullPolicy: Always
          env:
          - name: CLAMD_HOST
            value: localhost
          - name: CLAMD_PORT
            value: '3310'
          ports:
            - containerPort: 8091
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8091
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8091
        - name: clamd
          image: "monostream/clamav:0.99.3-r1"
          imagePullPolicy: Always
          ports:
          - containerPort: 3310
            name: api
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - readiness.sh
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 600
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
              - liveness.sh
            initialDelaySeconds: 90
            timeoutSeconds: 10
            periodSeconds: 300
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: muescheli
  labels:
    app: muescheli
spec:
  type: NodePort
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
      name: muescheli
  selector:
    app: muescheli
    release: muescheli
